# Generated by Django 6.0.5 on 2026-05-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_audio',
            field=models.BooleanField(default=False),
        ),
    ]
